/** 遴选全流程事件类型。系统状态只能通过这些事件改变。 */
export const Event = {
  // 届次与规则
  EDITION_CREATED: "EDITION_CREATED",
  RULES_FROZEN: "RULES_FROZEN",
  STAGE_CHANGED: "STAGE_CHANGED",

  // 提名与身份
  NOMINATION_SUBMITTED: "NOMINATION_SUBMITTED",
  PERSON_CREATED: "PERSON_CREATED", // 人工归并产生的规范自然人身份
  IDENTITY_LINKED: "IDENTITY_LINKED", // 多条提名（可跨类别）指向同一自然人
  CANDIDATES_MERGED: "CANDIDATES_MERGED", // 重复候选资格吸收（同类别重复提名）
  TEAM_LINKED: "TEAM_LINKED",

  // 成果与证据
  ACHIEVEMENT_DECLARED: "ACHIEVEMENT_DECLARED",
  ACHIEVEMENT_CREDIT_DECIDED: "ACHIEVEMENT_CREDIT_DECIDED",
  EVIDENCE_SUBMITTED: "EVIDENCE_SUBMITTED",
  EVIDENCE_AMENDED: "EVIDENCE_AMENDED",
  FACT_VERDICT: "FACT_VERDICT",
  FACT_ELIGIBILITY_DECIDED: "FACT_ELIGIBILITY_DECIDED",
  CANDIDATE_CONSENT: "CANDIDATE_CONSENT",

  // 评委与评审
  REVIEWER_REGISTERED: "REVIEWER_REGISTERED",
  COI_DECLARED: "COI_DECLARED",
  COI_WITHDRAWN: "COI_WITHDRAWN",
  SCORE_SUBMITTED: "SCORE_SUBMITTED",
  TIE_RESOLVED: "TIE_RESOLVED",
  ROUND_RESULT_RECORDED: "ROUND_RESULT_RECORDED",

  // 公示与异议
  PUBLICATION_PUBLISHED: "PUBLICATION_PUBLISHED",
  PUBLICATION_CORRECTED: "PUBLICATION_CORRECTED",
  OBJECTION_FILED: "OBJECTION_FILED",
  OBJECTION_VERDICT: "OBJECTION_VERDICT",
  EDITION_FINALIZED: "EDITION_FINALIZED",
};

export const Stage = {
  SETUP: "SETUP",
  NOMINATION: "NOMINATION",
  FACT_CHECK: "FACT_CHECK",
  PROFESSIONAL_REVIEW: "PROFESSIONAL_REVIEW",
  SOCIAL_REVIEW: "SOCIAL_REVIEW",
  DELIBERATION: "DELIBERATION",
  PUBLICITY: "PUBLICITY",
  OBJECTION: "OBJECTION",
  FINALIZED: "FINALIZED",
};

/** 阶段顺序，STAGE_CHANGED 只能向前推进。 */
export const STAGE_ORDER = [
  Stage.SETUP,
  Stage.NOMINATION,
  Stage.FACT_CHECK,
  Stage.PROFESSIONAL_REVIEW,
  Stage.SOCIAL_REVIEW,
  Stage.DELIBERATION,
  Stage.PUBLICITY,
  Stage.OBJECTION,
  Stage.FINALIZED,
];

/** 候选本人可授权公开的内容板块；未授权板块不得出现在公示中。 */
export const ConsentSection = {
  BASIC: "basic", // 姓名、机构、职务
  NOMINATOR: "nominator", // 推荐单位
  ACHIEVEMENTS: "achievements", // 事迹
  EVIDENCE_SOURCES: "evidence_sources", // 证明来源
  CONTRIBUTION: "contribution", // 在共同成果中的个人贡献
};
